<?php

return [
    'module' => 'MODULE 01',
    'title' => 'Accessible According to Whom?',
    'not_public' => true,

    'sessions' => [
        1 => [
            'label' => 'SESSION 01',
            'title' => 'Is This Accessible?',
            'run_of_show' => [
                '0-8 min: find HuskyCT/Blackboard teams and sit together',
                '8-23 min: student introductions',
                '23-33 min: course orientation',
                '33-36 min: reveal "Is this accessible?"',
                '36-51 min: free investigation',
                '51-58 min: debrief initial findings',
                '58-62 min: pivot to "According to whom?"',
                '62-68 min: reveal Challenge 01 team lenses',
                '68-75 min: begin authoritative-source research',
            ],
            'prompts' => [
                'How do you know?',
                'What makes that inaccessible?',
                'Could you test that?',
                'Can the AI actually observe what it is claiming?',
                'Is that bad design or inaccessible design? Are those necessarily the same thing?',
                'What standard are you using?',
                'Is that the actual authoritative source, or somebody describing it?',
            ],
            'intended_realization' => 'Students can probably identify potential accessibility problems, but they do not yet have a defensible framework for declaring an experience accessible.',
        ],
        2 => [
            'label' => 'SESSION 02',
            'title' => 'Build the Definition',
            'run_of_show' => [
                'Opening: students immediately open shared W3C resources and complete the Learn the Map exercise while instructor circulates.',
                'Lens work: teams continue assigned research with primary-source tracing and evidence checks.',
                'Cross-check: short informal exchange across teams, no formal presentations.',
                'Return to Design Futures: test with at least one method not used in Session 01.',
                'Studio: teams finish Challenge 01 brief and submit by EOD.',
            ],
            'sample_interface_synthesis' => [
                'Ask teams whether their Session 01 accessibility determination changed.',
                'Compare problems found through visual inspection, AI, automated testing, keyboard testing, and standards research.',
                'Reveal selected intentional defects progressively rather than presenting the whole answer key immediately.',
                'Use specific defects to introduce POUR and demonstrate how to locate a relevant WCAG success criterion.',
                'Emphasize that finding some WCAG failures does not prove that all accessibility barriers have been identified.',
                'End by asking what evidence would actually be required to make a stronger accessibility determination.',
            ],
            'synthesis_prompts' => [
                'How do you know?',
                'What did you test?',
                'What authority supports that claim?',
                'What still don\'t you know?',
            ],
            'intervention_points' => [
                'How do you know?',
                'Where did that claim come from?',
                'Is that a primary source?',
                'Does that source actually say what you think it says?',
                'Did you test this?',
                'Could an automated tool establish that?',
                'Could an AI actually observe that?',
                'What doesn\'t this evidence tell you?',
                'What did you miss the first time?',
            ],
            'if_students_need_wcag_help' => [
                'Do not default to a mini-lecture.',
                'Demonstrate one workflow only when needed:',
                '1. identify a suspected barrier in Design Futures;',
                '2. open WCAG Quick Reference;',
                '3. search or filter for the relevant concept;',
                '4. open the success criterion;',
                '5. inspect the Understanding page;',
                '6. decide whether the evidence actually supports the claim.',
                'Purpose: teach navigation and evidence-checking, not deliver full WCAG content.',
            ],
        ],
    ],

    'sample_experience' => [
        'route' => 'experiences.campus-event-registration',
        'title' => 'Design Futures 2026 Registration',
        'answer_key' => [
            [
                'issue' => 'Low contrast secondary copy',
                'implemented' => 'Metadata and helper text are intentionally styled with low-contrast gray against white.',
                'discovery' => 'Visual review, color contrast tools, or browser extension checks on smaller text.',
                'automation_likely' => true,
                'ai_likely' => true,
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.3 Contrast (Minimum)',
                'remediation' => 'Increase color contrast for all meaningful small text to meet minimum ratio requirements.',
            ],
            [
                'issue' => 'Availability status conveyed by color alone',
                'implemented' => 'Program track availability indicators use colored dots with no equivalent text or icon meaning.',
                'discovery' => 'Manual visual analysis, color-blind simulation, and interpretation checks.',
                'automation_likely' => false,
                'ai_likely' => true,
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color',
                'remediation' => 'Pair color indicators with explicit text, icons, or labels that communicate status independently.',
            ],
            [
                'issue' => 'Mouse-only program track selection',
                'implemented' => 'Primary track choices are non-semantic clickable cards without keyboard operability.',
                'discovery' => 'Keyboard-only testing and inspection of interactive semantics.',
                'automation_likely' => false,
                'ai_likely' => true,
                'wcag_principle' => 'Operable',
                'likely_sc' => '2.1.1 Keyboard, 4.1.2 Name, Role, Value',
                'remediation' => 'Use native form controls or fully accessible custom controls with keyboard support and semantics.',
            ],
            [
                'issue' => 'Reduced visible focus for key controls',
                'implemented' => 'Focus indicators are suppressed on major action links and submit controls.',
                'discovery' => 'Tab navigation and direct keyboard interaction.',
                'automation_likely' => true,
                'ai_likely' => true,
                'wcag_principle' => 'Operable',
                'likely_sc' => '2.4.7 Focus Visible',
                'remediation' => 'Restore a clear focus style with sufficient contrast and consistent visibility.',
            ],
            [
                'issue' => 'Insufficient image alternative quality',
                'implemented' => 'A meaningful event poster uses generic alternative text: "Event poster".',
                'discovery' => 'Manual content review comparing image information against provided text alternatives.',
                'automation_likely' => false,
                'ai_likely' => true,
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.1.1 Non-text Content',
                'remediation' => 'Provide concise alt text that captures the poster\'s purpose and key informational content.',
            ],
            [
                'issue' => 'Placeholder-only text inputs',
                'implemented' => 'Multiple registration fields rely on placeholders instead of persistent associated labels.',
                'discovery' => 'Inspection of form markup and screen reader/manual form navigation.',
                'automation_likely' => true,
                'ai_likely' => true,
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.3.1 Info and Relationships, 3.3.2 Labels or Instructions',
                'remediation' => 'Add explicit labels associated to each input, keeping placeholders optional and supplemental.',
            ],
            [
                'issue' => 'Required fields not conveyed programmatically',
                'implemented' => 'Required state is only shown visually with asterisks in placeholder text and hint copy.',
                'discovery' => 'Source inspection plus assistive-technology form announcement checks.',
                'automation_likely' => true,
                'ai_likely' => true,
                'wcag_principle' => 'Understandable',
                'likely_sc' => '3.3.2 Labels or Instructions, 1.3.1 Info and Relationships',
                'remediation' => 'Use true required semantics and clear field-level instruction text.',
            ],
            [
                'issue' => 'Validation errors not robustly associated',
                'implemented' => 'Error handling is visual and generic, without reliable field associations or focus management.',
                'discovery' => 'Submit invalid form data and evaluate announcements, focus behavior, and field associations.',
                'automation_likely' => false,
                'ai_likely' => true,
                'wcag_principle' => 'Understandable',
                'likely_sc' => '3.3.1 Error Identification, 3.3.3 Error Suggestion, 4.1.3 Status Messages',
                'remediation' => 'Create programmatic error summary + per-field associations and move focus intentionally.',
            ],
            [
                'issue' => 'Incorrect heading hierarchy',
                'implemented' => 'Visual section headings are styled well but semantic levels skip expected hierarchy.',
                'discovery' => 'Heading outline inspection via browser tools or accessibility extension.',
                'automation_likely' => true,
                'ai_likely' => true,
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.3.1 Info and Relationships, 2.4.6 Headings and Labels',
                'remediation' => 'Use a coherent heading order that matches document structure and navigation expectations.',
            ],
            [
                'issue' => 'Ambiguous repeated link text',
                'implemented' => 'Several contextual links reuse vague text such as "Learn more".',
                'discovery' => 'Link-list review and out-of-context screen reader link navigation.',
                'automation_likely' => true,
                'ai_likely' => true,
                'wcag_principle' => 'Operable',
                'likely_sc' => '2.4.4 Link Purpose (In Context)',
                'remediation' => 'Use link text that communicates destination or purpose without surrounding visual context.',
            ],
        ],
    ],
];
