<?php

return [
    'module' => 'MODULE 02',
    'title' => 'Can You See What Matters?',
    'not_public' => true,
    'sessions' => [
        3 => [
            'label' => 'SESSION 03',
            'run_of_show' => [
                'Opening: compare the three Challenge 01 briefs and return to "How do you know?"',
                'Transition: introduce visual perception as the next investigation problem.',
                'First Look: students use Campus Study Space Finder without prescribed testing methods.',
                'WAVE: demonstrate one or two findings, then let teams compare automated evidence with observation.',
                'Challenge 02: teams select a lens and begin investigation and redesign planning.',
            ],
            'prompts' => [
                'What seemed important in the interface?',
                'How did the interface communicate that importance?',
                'What changed when you could not rely on color, size, position, or contrast?',
                'What did WAVE expose?',
                'What did WAVE leave for human judgment?',
                'Did WAVE determine whether the experience was accessible?',
            ],
            'sample_experience_synthesis' => 'Reveal the answer key progressively. First ask what students noticed, then compare WAVE findings, then map a specific observation to a WCAG concept. Keep the distinction between a flagged issue and a complete accessibility determination visible.',
        ],
        4 => [
            'label' => 'SESSION 04',
            'run_of_show' => [
                'Test the view: teams choose methods that fit their lens.',
                'Compare methods: short informal cross-team exchange.',
                'Redesign: most of class is studio work.',
                'Test again: each team tests at least one important claim about its proposed solution.',
                'Finish Challenge 02 and submit through HuskyCT/Blackboard.',
            ],
            'prompts' => [
                'What exact claim are you testing?',
                'What result would count as improvement?',
                'What did the redesign change for the user?',
                'How do you know the redesign is actually better?',
            ],
        ],
    ],
    'sample_experience' => [
        'route' => 'experiences.campus-study-space-finder',
        'title' => 'Campus Study Space Finder',
        'answer_key' => [
            [
                'issue' => 'Low contrast secondary information',
                'lens' => 'Cyan Triangle - Color & Contrast',
                'where' => 'Room details, hours, seat counts, helper text, and the "Updated a few minutes ago" timestamp.',
                'implemented' => 'Secondary text uses a muted gray that looks intentional but is close to or below the required contrast for normal text.',
                'initial_notice' => 'The page feels calm and polished, but some supporting details take more effort to read.',
                'discovery' => 'Visual review and a focused contrast measurement of a specific text/background pair.',
                'testing' => 'Use WebAIM Contrast Checker or another contrast measurement tool; compare the result with WCAG 1.4.3.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.3 Contrast (Minimum)',
                'wave' => 'Likely to expose some contrast problems in the rendered page.',
                'wave_cannot' => 'It cannot determine whether every important visual distinction is readable in every user context or whether the redesign is usable for real people.',
                'remediation' => 'Choose text and surface colors that meet the applicable contrast requirement, then remeasure the actual rendered pair.',
            ],
            [
                'issue' => 'Availability conveyed by color alone',
                'lens' => 'Cyan Triangle - Color & Contrast',
                'where' => 'The green, amber, and red status dots on each recommended-space card.',
                'implemented' => 'Each space has a colored status dot and a page-level legend, but no equivalent status text is placed on the card beside the dot.',
                'initial_notice' => 'The dots look like familiar availability signals, while the seat or table count seems related but not identical.',
                'discovery' => 'Ask what "green," "amber," or "red" means without the legend, and compare the card across color conditions.',
                'testing' => 'Inspect the rendered card and check whether a text or non-color cue communicates the same status; map the claim to WCAG 1.4.1.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color',
                'wave' => 'Unlikely to determine the meaning conveyed by the color status or whether the legend is sufficient in context.',
                'wave_cannot' => 'It cannot decide whether users understand the status or whether another cue communicates the intended distinction.',
                'remediation' => 'Show an explicit status label or icon alongside color, and make the legend supplemental rather than essential.',
            ],
            [
                'issue' => 'Weak selected and filter states',
                'lens' => 'Cyan Triangle - Color & Contrast',
                'where' => 'The pale boundary around cards and inactive filter pills, especially against the light surface and in dark appearance.',
                'implemented' => 'Card and inactive-control boundaries use a restrained line color with insufficient non-text contrast in some presentation modes.',
                'initial_notice' => 'Cards and controls still look grouped, but their edges become easy to lose against the surrounding surface.',
                'discovery' => 'Compare selected and unselected controls at normal view and under a different display preference.',
                'testing' => 'Check the contrast of the selected component boundary or indicator against adjacent colors; map the relevant claim to WCAG 1.4.11.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.11 Non-text Contrast',
                'wave' => 'May expose some contrast information, but it is unlikely to understand the state relationship or whether the selected state is clear.',
                'wave_cannot' => 'It cannot establish that a user can identify the current selection or compare states reliably.',
                'remediation' => 'Use a stronger boundary, fill, icon, or text treatment and preserve the distinction under user display changes.',
            ],
            [
                'issue' => 'Text enlargement and reflow failure',
                'lens' => 'Amber Circle - Text, Scale & Reflow',
                'where' => 'The fixed-height card details region and minimum-width results grid.',
                'implemented' => 'The results strip has a fixed compact height and a minimum-width grid, so enlarged text and narrow effective viewports clip or force two-dimensional scrolling.',
                'initial_notice' => 'At the default size the three-line details fit neatly and the desktop comparison feels comfortable.',
                'discovery' => 'Increase browser zoom or text size, then narrow the viewport and look for clipping, overlap, or loss of the comparison task.',
                'testing' => 'Test at 200% zoom and a narrow effective viewport; compare the observed behavior with WCAG 1.4.4 and 1.4.10.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.4 Resize Text; 1.4.10 Reflow',
                'wave' => 'Unlikely to evaluate zoom, text enlargement, or reflow behavior as a complete user task.',
                'wave_cannot' => 'It cannot tell whether content remains available and understandable at enlarged text or narrow widths.',
                'remediation' => 'Remove fixed heights and minimum-width assumptions, allow cards to stack, and test the task at 200% zoom and narrow widths.',
            ],
            [
                'issue' => 'Visual hierarchy carries comparison meaning',
                'lens' => 'Violet Square - Visual Cues & Meaning',
                'where' => 'The first card is visually recommended through its top-right clipped corner marker and leftmost position.',
                'implemented' => 'The featured room is marked by a corner shape and position without a nearby "Recommended" label.',
                'initial_notice' => 'The first card feels preferred, but a user may not know whether that means best match, newest, or simply first.',
                'discovery' => 'Ask which space appears recommended and what evidence in the interface supports that reading.',
                'testing' => 'Compare the visual cue with explicit text and inspect the experience under light/dark or forced-colors presentation where available.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color; 1.4.11 Non-text Contrast, where applicable',
                'wave' => 'Unlikely to determine the intended meaning of size, position, or visual hierarchy.',
                'wave_cannot' => 'It cannot infer the designer\'s intended comparison or determine whether a user understands it.',
                'remediation' => 'Pair visual emphasis with a clear label or text explanation, and preserve the distinction when user display preferences change.',
            ],
            [
                'issue' => 'Text enlargement clips card details',
                'lens' => 'Amber Circle - Text, Scale & Reflow',
                'where' => 'The fixed-height `.finder-details` region inside each recommended-space card.',
                'implemented' => 'The compact detail region hides overflow, so wrapped metadata or hours can disappear when text is enlarged or spacing increases.',
                'initial_notice' => 'At the default size the three lines fit neatly and the cards feel evenly aligned.',
                'discovery' => 'Increase browser zoom or text size and inspect whether room details, hours, or feature markers remain available.',
                'testing' => 'Test at 200% zoom and with increased text or line spacing; compare content loss with WCAG 1.4.4 and 1.4.12.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.4 Resize Text; 1.4.12 Text Spacing',
                'wave' => 'Unlikely to evaluate text enlargement, spacing, or hidden overflow as a complete user task.',
                'wave_cannot' => 'It cannot tell whether content remains available and understandable at enlarged text or increased spacing.',
                'remediation' => 'Remove the fixed height and overflow clipping, allow the card to grow, and retest with enlarged text and spacing.',
            ],
            [
                'issue' => 'Minimum-width results strip requires horizontal scrolling',
                'lens' => 'Amber Circle - Text, Scale & Reflow',
                'where' => 'The recommended-space grid inside the horizontally scrolling results section.',
                'implemented' => 'The results grid keeps a 720px minimum width, so a narrow effective viewport preserves card widths and requires two-dimensional comparison or hides the right side.',
                'initial_notice' => 'The desktop three-card comparison is comfortable and the mobile view appears usable until the effective width becomes narrow.',
                'discovery' => 'Use 200% zoom or a narrow viewport and attempt to reach every card and action without losing the comparison context.',
                'testing' => 'Test at a 320 CSS-pixel effective width and at 200% zoom; compare horizontal scrolling with WCAG 1.4.10.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.10 Reflow',
                'wave' => 'Unlikely to evaluate the page at an effective narrow width or identify that ordinary content needs two-dimensional scrolling.',
                'wave_cannot' => 'It cannot establish that all cards and actions remain reachable and understandable when the viewport is narrow.',
                'remediation' => 'Let cards stack or resize within the available width and verify the comparison task without horizontal page scrolling.',
            ],
            [
                'issue' => 'Text and action collision at enlarged scale',
                'lens' => 'Amber Circle - Text, Scale & Reflow',
                'where' => 'The seat-count and "View space" row at the bottom of each card.',
                'implemented' => 'The row uses a single no-wrap flex line, so enlarged text can compress, collide, or push the action out of the card.',
                'initial_notice' => 'The short metadata and action align cleanly at the default desktop size.',
                'discovery' => 'Increase text size until the seat count and action compete for space, then check whether both remain legible and usable.',
                'testing' => 'Test at 200% zoom and with longer enlarged strings; compare the result with WCAG 1.4.4 and 1.4.10.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.4 Resize Text; 1.4.10 Reflow',
                'wave' => 'Unlikely to expose a collision that appears only after text enlargement.',
                'wave_cannot' => 'It cannot determine whether the comparison action remains easy to identify and activate at enlarged scale.',
                'remediation' => 'Allow the row to wrap or stack while preserving a clear action target and readable metadata.',
            ],
            [
                'issue' => 'Selected filter state depends on appearance',
                'lens' => 'Violet Square - Visual Cues & Meaning',
                'where' => 'The All spaces filter and whichever filter a user selects in the filter pill group.',
                'implemented' => 'Selection is communicated through a dark fill, contrasting border, and inset accent stripe without a visible "Selected" label.',
                'initial_notice' => 'The current filter is easy to spot at a glance, but the meaning is carried by styling rather than by text.',
                'discovery' => 'Compare active and inactive pills in grayscale, with forced colors where available, and after changing the filter.',
                'testing' => 'Record which visual properties communicate selection and whether a non-color cue remains; relate the finding to WCAG 1.4.1 and 1.4.11 where applicable.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color; 1.4.11 Non-text Contrast',
                'wave' => 'May identify contrast values, but it is unlikely to understand which pill is selected or whether the state is visually unambiguous.',
                'wave_cannot' => 'It cannot determine whether users can compare the state of the filter group or understand the visual treatment as selection.',
                'remediation' => 'Keep the visual distinction but add a clear textual state or persistent non-color indicator that survives display changes.',
            ],
            [
                'issue' => 'Icon-only feature markers lack a visible key',
                'lens' => 'Violet Square - Visual Cues & Meaning',
                'where' => 'The circular, diamond, filled-square, and outlined markers beneath card details.',
                'implemented' => 'Markers communicate power, silent zone, accessible entrance, or reservation through shape and hover text, while the page gives only a general clue that markers represent features.',
                'initial_notice' => 'The markers make the cards feel information-rich, but their specific meanings are not obvious without recognition or interaction.',
                'discovery' => 'Ask a student to identify each shape without hovering and compare recognition across cards.',
                'testing' => 'Test whether shape, spacing, and the contextual clue communicate the feature without relying on color alone; inspect against WCAG 1.4.1.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color, where color contributes; 1.3.3 Sensory Characteristics as a concept',
                'wave' => 'Unlikely to expose that an icon has an unclear visual meaning or that the general clue is insufficient.',
                'wave_cannot' => 'It cannot determine whether a user recognizes a shape or understands its feature meaning in context.',
                'remediation' => 'Provide a compact visual legend or short text labels while retaining shape as a quick-scan cue.',
            ],
            [
                'issue' => 'Shortlist selection relies on border and shadow treatment',
                'lens' => 'Violet Square - Visual Cues & Meaning',
                'where' => 'The selected room card after a user clicks a recommended-space card.',
                'implemented' => 'The chosen card is distinguished primarily by an accent border and soft outer shadow; the confirmation message is separated below the grid.',
                'initial_notice' => 'The card looks selected if the user notices the edge change, but the visual relationship is easy to miss among the other cards.',
                'discovery' => 'Select each card, compare selected and unselected boundaries, and temporarily remove the shadow or accent color.',
                'testing' => 'Compare the selected state in grayscale and dark appearance; assess whether more than color and a subtle boundary communicate the state.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.11 Non-text Contrast; 1.4.1 Use of Color, where color is relied upon',
                'wave' => 'May report the changed boundary contrast, but it is unlikely to understand the selection relationship or distance to the confirmation message.',
                'wave_cannot' => 'It cannot establish that users can identify the selected card or connect the visual state with the shortlist outcome.',
                'remediation' => 'Add a persistent text or icon state inside the selected card and make the selected boundary meet non-text contrast expectations.',
            ],
            [
                'issue' => 'Icon and position communicate recommendation',
                'lens' => 'Violet Square - Visual Cues & Meaning',
                'where' => 'The clipped corner marker at the top-right of the North Reading Room card and its first position.',
                'implemented' => 'The first card appears recommended through position and a corner treatment, without a nearby "Recommended" label.',
                'initial_notice' => 'The first card feels like the preferred result, but a user may not know whether that means best match, newest, or simply first.',
                'discovery' => 'Ask which result is recommended and what evidence supports that interpretation, then hide or restyle the corner marker.',
                'testing' => 'Compare the meaning when card order changes and inspect whether position, shape, or fill is doing the communication; relate the claim to WCAG 1.3.3.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.3.3 Sensory Characteristics',
                'wave' => 'Unlikely to infer the intended meaning of position or a clipped-corner visual marker.',
                'wave_cannot' => 'It cannot determine whether users understand why one card is visually prioritized or what the position signifies.',
                'remediation' => 'Add an explicit recommendation label and retain the corner treatment only as a supplementary scan cue.',
            ],
            [
                'issue' => 'Appearance preference exposes a weak boundary',
                'lens' => 'Cyan Triangle - Color & Contrast',
                'where' => 'Card and control borders when the operating system or browser uses dark appearance.',
                'implemented' => 'The dark palette keeps a low-contrast green-gray line that is visually coherent but difficult to distinguish from the dark surface.',
                'initial_notice' => 'The dark presentation feels intentional, while grouping and card edges become less certain on inspection.',
                'discovery' => 'Toggle light and dark appearance and compare the same card boundary and selected state in both modes.',
                'testing' => 'Measure the rendered border against the adjacent surface in each appearance mode; compare the claim with WCAG 1.4.11.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.11 Non-text Contrast',
                'wave' => 'May expose a contrast value in the currently rendered mode, but it will not test the alternate appearance automatically.',
                'wave_cannot' => 'It cannot establish that the component remains distinguishable across user-selected appearance preferences.',
                'remediation' => 'Define measured light and dark boundary tokens and verify both modes with the same component-state tests.',
            ],
        ],
    ],
];
