<?php

return [
    'module' => 'MODULE 02',
    'title' => 'Can You See What Matters?',
    'not_public' => true,
    'sessions' => [
        3 => [
            'label' => 'SESSION 03',
            'run_of_show' => [
                'Opening: compare the three Challenge 01 briefs and return to "How do you know?"',
                'Transition: introduce visual perception as the next investigation problem.',
                'First Look: students use Campus Study Space Finder without prescribed testing methods.',
                'WAVE: demonstrate one or two findings, then let teams compare automated evidence with observation.',
                'Challenge 02: teams select a lens and begin investigation and redesign planning.',
            ],
            'prompts' => [
                'What seemed important in the interface?',
                'How did the interface communicate that importance?',
                'What changed when you could not rely on color, size, position, or contrast?',
                'What did WAVE expose?',
                'What did WAVE leave for human judgment?',
                'Did WAVE determine whether the experience was accessible?',
            ],
            'sample_experience_synthesis' => 'Reveal the answer key progressively. First ask what students noticed, then compare WAVE findings, then map a specific observation to a WCAG concept. Keep the distinction between a flagged issue and a complete accessibility determination visible.',
        ],
        4 => [
            'label' => 'SESSION 04',
            'run_of_show' => [
                'Test the view: teams choose methods that fit their lens.',
                'Compare methods: short informal cross-team exchange.',
                'Redesign: most of class is studio work.',
                'Test again: each team tests at least one important claim about its proposed solution.',
                'Finish Challenge 02 and submit through HuskyCT/Blackboard.',
            ],
            'prompts' => [
                'What exact claim are you testing?',
                'What result would count as improvement?',
                'What did the redesign change for the user?',
                'How do you know the redesign is actually better?',
            ],
        ],
    ],
    'sample_experience' => [
        'route' => 'experiences.campus-study-space-finder',
        'title' => 'Campus Study Space Finder',
        'answer_key' => [
            [
                'issue' => 'Low contrast secondary information',
                'implemented' => 'Room details, hours, and helper text use pale gray text on white and pale blue surfaces.',
                'discovery' => 'Visual review and a focused contrast measurement of a specific text/background pair.',
                'testing' => 'Use WebAIM Contrast Checker or another contrast measurement tool; compare the result with WCAG 1.4.3.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.3 Contrast (Minimum)',
                'wave' => 'Likely to expose some contrast problems in the rendered page.',
                'wave_cannot' => 'It cannot determine whether every important visual distinction is readable in every user context or whether the redesign is usable for real people.',
                'remediation' => 'Choose text and surface colors that meet the applicable contrast requirement, then remeasure the actual rendered pair.',
            ],
            [
                'issue' => 'Availability conveyed by color alone',
                'implemented' => 'Each space has a colored status dot, but the status label is visually suppressed from the student-facing card.',
                'discovery' => 'Ask what "green," "amber," or "red" means without the legend, and compare the card across color conditions.',
                'testing' => 'Inspect the rendered card and check whether a text or non-color cue communicates the same status; map the claim to WCAG 1.4.1.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color',
                'wave' => 'Unlikely to determine the meaning conveyed by the color status or whether the legend is sufficient in context.',
                'wave_cannot' => 'It cannot decide whether users understand the status or whether another cue communicates the intended distinction.',
                'remediation' => 'Show an explicit status label or icon alongside color, and make the legend supplemental rather than essential.',
            ],
            [
                'issue' => 'Weak selected and filter states',
                'implemented' => 'The selected filter and selected room rely on a subtle border and a small color change.',
                'discovery' => 'Compare selected and unselected controls at normal view and under a different display preference.',
                'testing' => 'Check the contrast of the selected component boundary or indicator against adjacent colors; map the relevant claim to WCAG 1.4.11.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.11 Non-text Contrast',
                'wave' => 'May expose some contrast information, but it is unlikely to understand the state relationship or whether the selected state is clear.',
                'wave_cannot' => 'It cannot establish that a user can identify the current selection or compare states reliably.',
                'remediation' => 'Use a stronger boundary, fill, icon, or text treatment and preserve the distinction under user display changes.',
            ],
            [
                'issue' => 'Text enlargement and reflow failure',
                'implemented' => 'The results strip has a fixed compact height and a minimum-width grid, so enlarged text and narrow effective viewports clip or force two-dimensional scrolling.',
                'discovery' => 'Increase browser zoom or text size, then narrow the viewport and look for clipping, overlap, or loss of the comparison task.',
                'testing' => 'Test at 200% zoom and a narrow effective viewport; compare the observed behavior with WCAG 1.4.4 and 1.4.10.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.4 Resize Text; 1.4.10 Reflow',
                'wave' => 'Unlikely to evaluate zoom, text enlargement, or reflow behavior as a complete user task.',
                'wave_cannot' => 'It cannot tell whether content remains available and understandable at enlarged text or narrow widths.',
                'remediation' => 'Remove fixed heights and minimum-width assumptions, allow cards to stack, and test the task at 200% zoom and narrow widths.',
            ],
            [
                'issue' => 'Visual hierarchy carries comparison meaning',
                'implemented' => 'The featured room is marked by a larger card and a bright corner marker while equivalent text information is visually quiet.',
                'discovery' => 'Ask which space appears recommended and what evidence in the interface supports that reading.',
                'testing' => 'Compare the visual cue with explicit text and inspect the experience under light/dark or forced-colors presentation where available.',
                'wcag_principle' => 'Perceivable',
                'likely_sc' => '1.4.1 Use of Color; 1.4.11 Non-text Contrast, where applicable',
                'wave' => 'Unlikely to determine the intended meaning of size, position, or visual hierarchy.',
                'wave_cannot' => 'It cannot infer the designer\'s intended comparison or determine whether a user understands it.',
                'remediation' => 'Pair visual emphasis with a clear label or text explanation, and preserve the distinction when user display preferences change.',
            ],
        ],
    ],
];
