<?php

return [
    'module' => 'MODULE 03',
    'title' => 'What Does This Media Say?',
    'not_public' => true,
    'sessions' => [
        5 => [
            'label' => 'SESSION 05',
            'run_of_show' => [
                'Look back at Module 02: compare the green-blue trail sign and the role of color in communicating meaning.',
                'Transition: move from interface cues to media that carries information in its own right.',
                'Media has a job: define the core question and the difference between a visual or audio element being decorative, informative, or essential to understanding.',
                'In-class demo: project /demos/media-purpose and walk through the three examples.',
                'First Look: students spend a few minutes using the University Research Feature / Digital Story before the challenge is introduced.',
                'Challenge 03: teams begin identifying media purpose and likely alternatives.',
            ],
            'prompts' => [
                'What information would a user lose if they could not see or hear the media as presented?',
                'What is the media doing in context?',
                'Is the same message needed in every context?',
                'What information is essential, and what information is optional or decorative?',
                'What is the simplest credible alternative?',
            ],
            'sample_experience_synthesis' => 'Keep the challenge centered on purpose and alternative design. Do not allow students to reduce the problem to one generic rule like “write longer alt text.” Show that purpose, context, and media type all matter.',
        ],
        6 => [
            'label' => 'SESSION 06',
            'run_of_show' => [
                'One more look: brief reminder that the same media may need a different alternative depending on purpose.',
                'Test the alternative: students exchange one proposed alternative with someone outside their team before showing the original media.',
                'Revise: teams revise their Accessible Media Package based on peer interpretation and evidence.',
                'Finish Challenge 03: reserve the rest of the class for final work and submission.',
            ],
            'prompts' => [
                'What did the reviewer understand?',
                'What questions remain?',
                'What do you need to add, remove, or clarify?',
                'How do you know the alternative preserves the important information?',
            ],
        ],
    ],
    'sample_experience' => [
        'route' => 'experiences.university-research-story',
        'title' => 'University Research Feature / Digital Story',
        'answer_key' => [
            [
                'media_item' => 'Hero editorial photo',
                'purpose' => 'Establish campus atmosphere, project identity, and emotional context for the story.',
                'problem' => 'The image may be visually interesting, but the exact people, setting, or relationship between the elements is not the key point of the story. Students may treat it as purely captioned information when it is mostly contextual.',
                'treatment' => 'Likely a concise, non-verbose alternative or decorative treatment if the surrounding text already communicates the story context. If the photo identifies a specific place or event, the alternative should identify it clearly without over-describing every detail.',
                'guidance' => 'W3C Images Tutorial: informative and decorative image guidance; W3C Images Tutorial: complex image guidance when the photo is paired with additional data or story meaning.',
                'wcag' => '1.1.1 Non-text Content',
                'misconception' => 'Students often assume a hero image always needs a full description describing every visible object because it feels important.',
                'discussion_question' => 'What makes an image essential to the story, and what is only atmosphere?',
                'range' => 'Acceptable answers include a short description of the scene, a decorative null treatment, or a nearby caption that explains why the image matters.',
                'requirements' => 'Requirements/principles: decide whether the image is informative or decorative and keep the alternative aligned with the real purpose in context.',
                'judgment' => 'Reasonable editorial judgment: a concise scene description may be accepted when the image is contextual, while a more specific note could be justified if the location or subject matters to the story.',
            ],
            [
                'media_item' => 'Informational photo of lab work',
                'purpose' => 'Illustrate a real moment in the research project and communicate that the work is hands-on, collaborative, and active.',
                'problem' => 'A generic alt text such as “Students working in a laboratory” does not preserve the specific context that makes the image meaningful in the story.',
                'treatment' => 'A short but specific description is likely appropriate. The alt text should include the meaningful detail that the scene represents in context, such as the equipment, setup, collaboration, or the experimental moment being discussed.',
                'guidance' => 'W3C Images Tutorial: informative images; Understanding WCAG 2.2: 1.1.1 Non-text Content.',
                'wcag' => '1.1.1 Non-text Content',
                'misconception' => 'Students sometimes think a generic description is safe because it technically names the content, but context can make a generic label materially incomplete.',
                'discussion_question' => 'Does the page need the image to communicate a specific fact, emotion, or relationship, or is it mostly a humanizing visual?',
                'range' => 'Acceptable solutions include a short descriptive sentence naming the activity and relevant details or a nearby caption that makes the story context explicit.',
                'requirements' => 'Requirements/principles: the alternative must preserve the information the image contributes in context, not just identify the object type.',
                'judgment' => 'Reasonable editorial judgment: an alternative may emphasize the collaboration, instrument setup, or the research activity depending on what the story is about.',
            ],
            [
                'media_item' => 'Decorative image with overly verbose alt text',
                'purpose' => 'Add visual atmosphere or polish without communicating required information.',
                'problem' => 'The decorative image has an alt attribute that lists almost every visible element, so the user receives a long description of content that is intentionally not important to the task or story.',
                'treatment' => 'Use a null or decorative treatment rather than describing the entire scene in detail. The image should not force users to process information they do not need.',
                'guidance' => 'W3C Decorative Images and W3C Images Tutorial: decorative images.',
                'wcag' => '1.1.1 Non-text Content',
                'misconception' => 'Students often think a decorative image must still be described in some way to be “complete.” The principle is to avoid unnecessary information when the image adds no real value.',
                'discussion_question' => 'What happens when the image is there mainly to create atmosphere and not to communicate a fact that users need?',
                'range' => 'Acceptable solutions include an empty alt attribute, a decorative treatment, or a nearby caption that does not narrate the decorative visual.',
                'requirements' => 'Requirements/principles: do not create needless description when the image is decorative and not functionally informative.',
                'judgment' => 'Reasonable editorial judgment: the visual may still be aesthetically valuable, but the alternative should remain minimal and not become a cluttered “all details” readout.',
            ],
            [
                'media_item' => 'Chart showing enrollment over time',
                'purpose' => 'Communicate growth, change, or comparison over time with a visual pattern that is easy to scan.',
                'problem' => 'The chart has an alt string that only identifies the object, such as “Bar chart showing enrollment over time.” The image omits the actual trend, comparison, and conclusion that matter to the story.',
                'treatment' => 'A brief identification should be paired with context and a concise explanation of the pattern or a longer description with the actual values. A data table or surrounding prose may be the best equivalent if the full chart is too complex for a short alt string.',
                'guidance' => 'W3C Complex Images and W3C Images Tutorial: informative and complex images.',
                'wcag' => '1.1.1 Non-text Content',
                'misconception' => 'Students often assume a single comprehensive alt string is always the answer. In complex visuals, the important information may belong in nearby text, a more structured data table, or a longer description.',
                'discussion_question' => 'What must a user know about the graph to understand the project’s results, and what is only a visual flourish?',
                'range' => 'Acceptable solutions include a concise summary of the trend, a longer descriptive paragraph, a table of values, or a combination of short identification plus surrounding explanatory text.',
                'requirements' => 'Requirements/principles: preserve the key message and the relevant data relationships, not just the object type.',
                'judgment' => 'Reasonable editorial judgment: the right balance depends on whether the chart is a quick visual summary or a central piece of evidence in the story.',
            ],
            [
                'media_item' => 'Poster-like infographic with key text embedded in an image',
                'purpose' => 'Present a compact visual summary of the research taking place, with important conclusions expressed as text inside the graphic.',
                'problem' => 'The infographic contains text that is visually meaningful, but the alternative currently does not preserve it. A user cannot access the conclusions if they cannot see the image.',
                'treatment' => 'Provide the text as real text in the page wherever practical, or create an accessible summary that preserves the core statements, not just the visual description of the layout.',
                'guidance' => 'W3C Images Tutorial: images of text and complex images; W3C Images Tutorial: informative images.',
                'wcag' => '1.1.1 Non-text Content',
                'misconception' => 'Students often treat an image of text as a picture that only needs identification. When the text itself carries meaning, the alternative must preserve that textual content or an equivalent summary.',
                'discussion_question' => 'If the key message is expressed visually as text, is the alternative supposed to reproduce the wording or to preserve the meaning?',
                'range' => 'Acceptable solutions include the text as visible HTML, a descriptive summary of the key points, or a nearby accessible version of the same statements.',
                'requirements' => 'Requirements/principles: if the text itself is information, that information must be available in an accessible text form.',
                'judgment' => 'Reasonable editorial judgment: the team can choose whether to preserve the precise wording or to summarize the core findings while keeping the essential meaning intact.',
            ],
            [
                'media_item' => 'Audio clip with spoken content and an excerpt transcript',
                'purpose' => 'Let the user hear the project director explain the initiative and why it matters.',
                'problem' => 'The audio is present but the transcript is incomplete or missing the meaningful context. The user may lose the purpose and specific claims if the audio cannot be heard.',
                'treatment' => 'Provide a transcript or accessible text version of the audio. If the audio includes important non-speech cues, they should also be described or noted.',
                'guidance' => 'W3C transcripts, W3C captions and subtitles, and W3C description of visual information.',
                'wcag' => '1.1.1 Non-text Content; 1.2.1 Audio-only and Video-only (Prerecorded)',
                'misconception' => 'Students often think captions are enough for audio-only content. A transcript is still useful for review, search, and understanding details that are not easy to capture in real time.',
                'discussion_question' => 'What information is lost when the audio is unavailable, and what kind of text access would preserve that meaning?',
                'range' => 'Acceptable solutions include a complete transcript, a shorter summary plus key quotes, or a transcript with notes for non-speech audio if relevant.',
                'requirements' => 'Requirements/principles: preserve spoken information and any meaningful non-speech audio in a form users can access.',
                'judgment' => 'Reasonable editorial judgment: a transcript may be complete or summarized, but it should preserve the key claims and any important sound cues.',
            ],
            [
                'media_item' => 'Short video with spoken dialogue and a critical visual action',
                'purpose' => 'Show both the narrative and the material change in the project itself, such as a prototype being tested or a visual state change that is not mentioned aloud.',
                'problem' => 'If the video has captions for dialogue but no description of the visual action, a user who cannot see the video may miss the key fact that changes the story. If the user cannot hear the audio, they may miss the spoken explanation that gives context for the visual decision.',
                'treatment' => 'Use captions for spoken content, transcripts for audio information, and concise description of the meaningful visual action that is not explained aloud. The combination depends on what is essential to understanding the event.',
                'guidance' => 'W3C Captions and Subtitles, W3C Transcripts, and W3C Description of Visual Information.',
                'wcag' => '1.2.2 Captions (Prerecorded); 1.2.3 Audio Description or Media Alternative (Prerecorded)',
                'misconception' => 'Students often reduce the problem to “captions are missing” and ignore the visual channel. The more important question is what information is carried by each channel and which essential details are not duplicated.',
                'discussion_question' => 'What important information is only visible, and what important information is only spoken?',
                'range' => 'Acceptable solutions include captions plus a concise description of the key visual action, a transcript with a note about important visual changes, or a nearby text summary that covers both channels.',
                'requirements' => 'Requirements/principles: identify the information in both the auditory and visual channels and provide alternatives for each where it matters to understanding.',
                'judgment' => 'Reasonable editorial judgment: some video scenes may only need a shorter description if the action is obvious from context, while others require more explicit description if the story depends on it.',
            ],
        ],
    ],
];
