<?php

return [
    'module' => 'MODULE 05',
    'title' => 'What Is the Interface Actually Made Of?',
    'not_public' => true,
    'sample_experience' => [
        'title' => 'MakerMap',
        'answer_key' => [
            [
                'number' => 1,
                'stage' => 'About MakerMap / Accessibility',
                'module' => 'Module 01',
                'issue' => 'Unsupported automated-testing and compliance claim',
                'where' => 'The section states: “MakerMap passed WAVE with no errors and meets WCAG 2.1 AA and Section 508 accessibility requirements.”',
                'why_it_matters' => 'A clean automated scan cannot establish WCAG conformance. WCAG is a technical standard, not itself a law. Section 508 directly governs federal-agency ICT, not generally the legal basis for a fictional public university service. Legal and institutional conclusions need authoritative, correctly scoped evidence.',
                'source' => 'W3C WAI conformance-evaluation guidance; WCAG; ADA Title II and Section 504 authorities; U.S. Access Board Section 508 scope; relevant institutional policy.',
                'remediation' => 'Remove the blanket claim. Make only appropriately scoped statements supported by documented evaluation and authoritative legal/institutional context.',
                'verification' => 'Trace each claim to current testing records and authoritative sources; confirm that tool output is not represented as proof of conformance.',
            ],
            [
                'number' => 2,
                'stage' => 'Available Spaces',
                'module' => 'Module 02',
                'issue' => 'Card availability depends on color alone',
                'where' => 'Cards use green, amber, and red dots without a card-level status word or distinct non-color cue. A separate legend labels the colors Available, Limited, and Busy.',
                'why_it_matters' => 'A person who cannot distinguish the colors cannot determine the availability of each individual space.',
                'source' => 'WCAG 1.4.1 Use of Color.',
                'remediation' => 'Pair each card status with text or another meaningful non-color indicator.',
                'verification' => 'Review each card in grayscale and confirm the status remains clear without referring to color.',
            ],
            [
                'number' => 3,
                'stage' => 'Available Spaces',
                'module' => 'Module 02',
                'issue' => 'Important hours metadata has insufficient text contrast',
                'where' => 'Operating hours use #AEB3AE on white in each space card.',
                'why_it_matters' => 'Hours determine whether a student can use a space and the normal-size text is below the required minimum contrast.',
                'source' => 'WCAG 1.4.3 Contrast (Minimum).',
                'remediation' => 'Increase contrast for the hours text without changing its meaning or relying on enlargement.',
                'verification' => 'Measure the rendered foreground/background contrast and recheck the final colors in context.',
            ],
            [
                'number' => 4,
                'stage' => 'Find a Space',
                'module' => 'Module 02',
                'issue' => 'Unselected filter boundary has insufficient non-text contrast',
                'where' => 'The unselected filter-chip border is #E9EFE8 against the page background #FBFCF8; the text label remains readable.',
                'why_it_matters' => 'The faint boundary makes the filter control difficult to identify as a distinct component before selection.',
                'source' => 'WCAG 1.4.11 Non-text Contrast.',
                'remediation' => 'Use a boundary or other visual indicator with sufficient contrast to distinguish the unselected control from its background.',
                'verification' => 'Measure the component boundary contrast against adjacent colors and inspect selected/unselected states.',
            ],
            [
                'number' => 5,
                'stage' => 'Digital Fabrication Lab',
                'module' => 'Module 02',
                'issue' => 'Text enlargement clips meaningful equipment and preparation details',
                'where' => 'The card places equipment and prerequisite content inside a 10.5rem fixed-height region with overflow hidden.',
                'why_it_matters' => 'At substantial enlargement, relevant equipment and preparation instructions become unavailable.',
                'source' => 'WCAG 1.4.4 Resize Text; WCAG 1.4.10 Reflow when applicable.',
                'remediation' => 'Allow this content region to expand and wrap rather than clipping meaningful text.',
                'verification' => 'Test at 200% text enlargement and a narrow reflow viewport; verify all equipment and prerequisite information remains available.',
            ],
            [
                'number' => 6,
                'stage' => 'Getting There',
                'module' => 'Module 03',
                'issue' => 'Complex campus map has an inadequate text alternative',
                'where' => 'The informative image has exactly alt="Campus makerspace map". The graphic contains four space locations, Central Walk, parking/drop-off, an accessible entrance, and elevator information; no equivalent directions appear elsewhere.',
                'why_it_matters' => 'The generic alternative does not provide enough location or route information to plan a visit.',
                'source' => 'WCAG 1.1.1 Non-text Content; W3C WAI Images Tutorial for complex images.',
                'remediation' => 'Provide a concise alternative and an adjacent structured description of the locations and wayfinding details.',
                'verification' => 'With the image unavailable, confirm a visitor can determine relevant locations and plan arrival using text.',
            ],
            [
                'number' => 7,
                'stage' => 'Digital Fabrication Lab',
                'module' => 'Module 03',
                'issue' => 'Informative fabrication illustration has no alt attribute',
                'where' => 'The fabrication-studio illustration shows a desktop fabrication machine and a printed prototype, but its img element has no alt attribute.',
                'why_it_matters' => 'The image contributes identifying context about the studio, but no text alternative is supplied.',
                'source' => 'WCAG 1.1.1 Non-text Content; W3C WAI Images Tutorial.',
                'remediation' => 'Add concise alt text communicating the image’s useful context, or make the image decorative only if it no longer conveys information.',
                'verification' => 'Inspect the image in a screen reader and with images disabled; verify a meaningful alternative is exposed.',
            ],
            [
                'number' => 8,
                'stage' => 'Media Production Studio',
                'module' => 'Module 03',
                'issue' => 'Informative media-studio illustration has a generic alt value',
                'where' => 'The media-studio illustration shows a camera setup and recording subject, but its alternative is alt="Lab photo".',
                'why_it_matters' => 'The alternative does not convey the useful recording-studio context visible in the image.',
                'source' => 'WCAG 1.1.1 Non-text Content; W3C WAI Images Tutorial.',
                'remediation' => 'Replace the generic alternative with a brief description of the relevant studio/recording content.',
                'verification' => 'Inspect the accessible name and confirm it conveys the image’s useful information without relying on the visual.',
            ],
            [
                'number' => 9,
                'stage' => 'Before You Visit',
                'module' => 'Module 03',
                'issue' => 'W3C prerecorded video has a transcript but no synchronized captions',
                'where' => 'MakerMap embeds https://media.w3.org/wai/accessibility-intro/intro.mp4. The visible W3C transcript is present, but no caption track is attached.',
                'why_it_matters' => 'The transcript is not synchronized text for people who need captions while watching the prerecorded speech.',
                'source' => 'WCAG 1.2.2 Captions (Prerecorded); W3C WAI video page and captions guidance.',
                'remediation' => 'Add accurate synchronized captions and retain the transcript as an additional text alternative.',
                'verification' => 'Play the video muted and confirm captions are synchronized and complete against the spoken content.',
            ],
            [
                'number' => 10,
                'stage' => 'Find a Space',
                'module' => 'Module 04',
                'issue' => 'Filters are pointer-only',
                'where' => 'Filter chips are non-focusable spans with click handlers. Pointer activation changes results, but Tab cannot reach them.',
                'why_it_matters' => 'Keyboard users cannot apply filters to identify a space for their project.',
                'source' => 'WCAG 2.1.1 Keyboard; W3C guidance on native interactive controls.',
                'remediation' => 'Use keyboard-operable controls with appropriate focus and activation behavior.',
                'verification' => 'Attempt to reach and activate every filter using only a keyboard, then compare with pointer results.',
            ],
            [
                'number' => 11,
                'stage' => 'Digital Fabrication Lab',
                'module' => 'Module 04',
                'issue' => 'Laser safety requirement is hover-only',
                'where' => 'Pointer hover over “Laser cutter” reveals “Safety orientation certification required.” Keyboard focus does not expose it, and it is not repeated elsewhere.',
                'why_it_matters' => 'A student who cannot hover may not learn an important prerequisite before selecting the space.',
                'source' => 'WCAG 1.4.13 Content on Hover or Focus; WCAG 2.1.1 Keyboard as applicable.',
                'remediation' => 'Make the requirement persistently available or expose it on both hover and keyboard focus.',
                'verification' => 'Test with pointer and keyboard. Confirm the requirement can be discovered without hover and is available while approached.',
            ],
            [
                'number' => 12,
                'stage' => 'Available Spaces',
                'module' => 'Module 04',
                'issue' => 'Save buttons have no visible focus treatment',
                'where' => 'All four native Save buttons remain keyboard-operable, but the .maker-save:focus-visible rule suppresses their outline and focus shadow.',
                'why_it_matters' => 'Keyboard users may lose track of which space action currently has focus.',
                'source' => 'WCAG 2.4.7 Focus Visible; WCAG 2.4.11 Focus Not Obscured (Minimum) where relevant.',
                'remediation' => 'Provide a visible focus indicator with sufficient contrast and area on each Save control.',
                'verification' => 'Tab through all four Save buttons and confirm focus is visibly identifiable.',
            ],
            [
                'number' => 13,
                'stage' => 'Available Spaces',
                'module' => 'Module 05',
                'issue' => 'Available Spaces is styled text rather than a semantic heading',
                'where' => 'The visible title uses a styled div. Other major section titles use h2 elements.',
                'why_it_matters' => 'Heading navigation and page structure omit this visually prominent section title.',
                'source' => 'WCAG 1.3.1 Info and Relationships; WCAG 2.4.6 Headings and Labels; W3C WAI Headings Tutorial.',
                'remediation' => 'Use a semantic heading at the appropriate level while retaining its current visual style.',
                'verification' => 'Inspect heading structure and navigate by headings; confirm Available Spaces appears in the expected sequence.',
            ],
            [
                'number' => 14,
                'stage' => 'Textiles & Prototyping Lab',
                'module' => 'Module 05',
                'issue' => 'Icon-only Save button has no accessible name',
                'where' => 'The native button contains only an SVG marked aria-hidden="true" and has no accessible naming source.',
                'why_it_matters' => 'Assistive technology exposes a button without a purpose, making it indistinguishable from other unnamed controls.',
                'source' => 'WCAG 4.1.2 Name, Role, Value; W3C WAI button and accessible-name guidance.',
                'remediation' => 'Give the button a useful name identifying the Save action and the space.',
                'verification' => 'Inspect its computed accessible name and test the control with a screen reader.',
            ],
            [
                'number' => 15,
                'stage' => 'Electronics Workshop',
                'module' => 'Module 05',
                'issue' => 'Disclosure does not expose its expanded state',
                'where' => 'The native button visually toggles its panel and has aria-controls, but it does not update or expose aria-expanded.',
                'why_it_matters' => 'The panel changes while programmatic state remains unavailable to assistive technology.',
                'source' => 'WCAG 4.1.2 Name, Role, Value; WAI-ARIA Authoring Practices Guide disclosure pattern.',
                'remediation' => 'Expose and update expanded/collapsed state or use a native disclosure element.',
                'verification' => 'Activate by keyboard and inspect the accessibility tree or screen-reader announcement in both states.',
            ],
            [
                'number' => 16,
                'stage' => 'Request an Orientation',
                'module' => 'Module 05',
                'issue' => 'Accessible name conflicts with the visible email label',
                'where' => 'The visible label is “University email,” while aria-label="Username" overrides the field name.',
                'why_it_matters' => 'The announced name does not match the visible label, which can interfere with speech input and field understanding.',
                'source' => 'WCAG 2.5.3 Label in Name; WCAG 3.3.2 Labels or Instructions.',
                'remediation' => 'Remove the conflicting aria-label and use the associated visible label as the accessible name.',
                'verification' => 'Inspect the computed name and test field navigation; verify that University email is exposed.',
            ],
            [
                'number' => 17,
                'stage' => 'Request an Orientation',
                'module' => 'Module 05',
                'issue' => 'Project title relies on placeholder-only identification',
                'where' => 'The Project title input has placeholder="Project title" but no persistent visible label or other naming relationship.',
                'why_it_matters' => 'The prompt disappears as the user types and does not provide a stable visible label for the field.',
                'source' => 'WCAG 3.3.2 Labels or Instructions; WCAG 1.3.1 Info and Relationships.',
                'remediation' => 'Add a persistent visible label associated with the input; retain placeholder only as supplemental guidance.',
                'verification' => 'Inspect the field before and after typing and confirm its purpose remains visible and programmatically named.',
            ],
            [
                'number' => 18,
                'stage' => 'Request an Orientation',
                'module' => 'Module 05',
                'issue' => 'Experience level choices lack a programmatic group relationship',
                'where' => '“Experience level” appears visually above three individually labeled radios, but the controls are not grouped by fieldset/legend or an equivalent semantic relationship.',
                'why_it_matters' => 'Users navigating choices individually may not receive the shared question context that relates the options.',
                'source' => 'WCAG 1.3.1 Info and Relationships; W3C WAI Forms Tutorial on grouping controls.',
                'remediation' => 'Use a fieldset and legend or another appropriate semantic grouping relationship while preserving each option label.',
                'verification' => 'Inspect the accessibility tree and navigate each radio with a screen reader; confirm the shared question is exposed as group context.',
            ],
            [
                'number' => 19,
                'stage' => 'Request an Orientation',
                'module' => 'Module 05',
                'issue' => 'Missing Preferred space receives only a general error',
                'where' => 'Submitting with no Preferred space visually highlights its group and shows “Please check the highlighted fields.” No specific error names Preferred space or is associated with the group.',
                'why_it_matters' => 'Users who cannot locate the visual highlight are not told which choice is missing or how to recover.',
                'source' => 'WCAG 3.3.1 Error Identification; WCAG 3.3.3 Error Suggestion where applicable.',
                'remediation' => 'Identify Preferred space in a visible, programmatically associated error and communicate the error beyond color/border.',
                'verification' => 'Submit with only Preferred space missing and inspect both visual and screen-reader feedback; confirm the affected group and correction are identified.',
            ],
            [
                'number' => 20,
                'stage' => 'Request an Orientation',
                'module' => 'Module 05',
                'issue' => 'Successful request status is visual only',
                'where' => 'A successful submit displays “Orientation request sent.” in a paragraph without a status role or live-region semantics.',
                'why_it_matters' => 'A user who is not monitoring the visual page may not be informed that submission succeeded.',
                'source' => 'WCAG 4.1.3 Status Messages; WAI-ARIA status role guidance.',
                'remediation' => 'Expose the update through an appropriate status mechanism without unnecessarily moving focus.',
                'verification' => 'Submit valid data while monitoring with a screen reader; confirm the success status is announced and remains visible.',
            ],
        ],
        'intentionally_correct' => [
            ['title' => 'Page structure and navigation', 'why' => 'MakerMap has a descriptive page title, one h1, a main landmark, functioning in-page links, and semantic major headings except the one planned generic title.'],
            ['title' => 'Comparison table', 'why' => 'The table uses native table, thead, tbody, th, and td elements with column and row scope.'],
            ['title' => 'Ordinary controls and disclosures', 'why' => 'Save controls are native buttons; three disclosure controls communicate state; the fourth remains keyboard-operable and only omits state.'],
            ['title' => 'Most form fields and errors', 'why' => 'Full name, email, time, project title aside, and accommodation needs use the current form patterns; ordinary errors are specific and associated, and valid values persist after errors. Preferred space alone has the planned vague error.'],
            ['title' => 'Client-only behavior', 'why' => 'Filtering, saves, reset, validation, and simulated success run locally; no form data is sent or persisted.'],
            ['title' => 'Focus, keyboard, and responsive behavior', 'why' => 'Ordinary controls show focus and work by keyboard; only filters, hover detail, and Save focus treatment have planned issues. The layout responds except for the single constrained text region.'],
            ['title' => 'Media and body content', 'why' => 'The map is informative and intentionally has weak alt; the video has a visible W3C transcript and no autoplay. Other content remains structured and readable.'],
        ],
        'non_failures' => [
            ['title' => 'Card-heavy layout and rounded corners', 'why' => 'Aesthetic choices are not automatically accessibility failures when content and controls remain usable.'],
            ['title' => 'Amount of white space', 'why' => 'A preference for denser layout alone does not establish a barrier or criterion failure.'],
            ['title' => 'Ordering of the four studios', 'why' => 'The order is a product decision and does not itself contradict a task or semantic relationship.'],
            ['title' => 'Space-description wording', 'why' => 'Copy may be revised for tone, but subjective wording preferences are not evidence of an accessibility failure.'],
            ['title' => 'Table appearance and icon styling', 'why' => 'The comparison table’s visual treatment and use of icons alongside text are reasonable design choices; its semantics are sound.'],
        ],
    ],
];
