<?php

return [
    'module' => 'MODULE 05',
    'title' => 'What Does the Interface Actually Say?',
    'not_public' => true,

    'sample_experience' => [
        'route' => 'experiences.module05.design-futures-registration',
        'title' => 'Design Futures 2026 Registration',
        'answer_key' => [
            [
                'number' => 1,
                'stage' => 'Explore the Event',
                'module' => 'Module 01',
                'issue' => 'Unsupported accessibility claim',
                'where' => 'Footer disclosure link: Accessibility page contains the statement, “Accessibility verified: WAVE found 0 errors. This site meets WCAG 2.1 AA and Section 508 requirements.”',
                'why_it_matters' => 'The claim presents a compliance status without explaining the testing method, timeframe, or scope. Users and stakeholders may assume conformance where none has been established.',
                'source' => 'WCAG and accessibility policy guidance; legal and institutional context matters; automated tooling does not establish conformance.',
                'remediation' => 'Replace the unsupported statement with a fact-based, scoped disclosure that identifies the testing method, date, scope, and applicable standard or institutional policy context.',
                'verification' => 'Review the wording against the actual testing method and policy context. Confirm that the statement names the standard or policy accurately and avoids unsupported legal claims.',
                'grading_nuance' => 'This is an evidence and authority issue, not merely a style complaint.',
            ],
            [
                'number' => 2,
                'stage' => 'Explore the Event',
                'module' => 'Module 02',
                'issue' => 'Low-contrast event metadata',
                'where' => 'Event detail metadata section uses foreground #9CA3AF on white background for time, building, room, or registration deadline.',
                'why_it_matters' => 'Normal-size text is difficult to read for many users, especially at standard viewing conditions or on displays with glare.',
                'source' => 'WCAG 1.4.3 Contrast (Minimum)',
                'remediation' => 'Increase the contrast ratio for the relevant metadata so it remains readable at normal text size.',
                'verification' => 'Use a contrast checker and inspect the text at normal size to confirm it remains readable without strain.',
                'grading_nuance' => 'This is a meaningful accessibility issue because it affects a specific factual metadata region, not the full page.',
            ],
            [
                'number' => 3,
                'stage' => 'Explore the Event',
                'module' => 'Module 03',
                'issue' => 'Promotional video has transcript but no synchronized captions',
                'where' => 'Short promotional video includes a transcript but no timed captions or closed captions track.',
                'why_it_matters' => 'Users who cannot hear the spoken content lose important event information, including schedule and program details.',
                'source' => 'WCAG 1.2.2 Captured Audio-only and Video-only; 1.2.3 Audio Description or Media Alternative (Prerecorded)',
                'remediation' => 'Add synchronized captions and ensure the transcript is clearly labeled as an alternative to the audio content.',
                'verification' => 'Compare the spoken content with the transcript and confirm that the captions properly align with relevant portions of the video.',
                'grading_nuance' => 'Do not score additional video defects beyond this single issue.',
            ],
            [
                'number' => 4,
                'stage' => 'Choose a Workshop',
                'module' => 'Module 02',
                'issue' => 'Seat status depends on color alone',
                'where' => 'Workshop cards show green, amber, and red indicators only; the status is not repeated in text or another non-color cue.',
                'why_it_matters' => 'Users who cannot distinguish red/amber/green or who rely on text descriptions cannot understand availability without additional context.',
                'source' => 'WCAG 1.4.1 Use of Color',
                'remediation' => 'Pair the color with a textual label such as “Open,” “Limited,” or “Nearly full,” or use another non-color signal consistently.',
                'verification' => 'Inspect the cards in grayscale and confirm that status remains understandable without relying on color alone.',
                'grading_nuance' => 'This is a deliberate color-only communication issue, not a general criticism of the workshop layout.',
            ],
            [
                'number' => 5,
                'stage' => 'Choose a Workshop',
                'module' => 'Module 03',
                'issue' => 'Venue map has inadequate alternative text',
                'where' => 'The venue map uses alt="Venue map" with no meaningful equivalent directions, entrances, or route information.',
                'why_it_matters' => 'Users who cannot perceive the image miss the route, entrances, check-in point, and wayfinding information necessary for attending the event.',
                'source' => 'WCAG 1.1.1 Non-text Content',
                'remediation' => 'Provide a text alternative or adjacent summary that communicates the key information the map conveys, including entrances and route guidance.',
                'verification' => 'Ask whether a user without the image would still know the main entrance, accessible entrance, check-in location, and route into the venue.',
                'grading_nuance' => 'The map is an important informational graphic, not decorative art.',
            ],
            [
                'number' => 6,
                'stage' => 'Choose a Workshop',
                'module' => 'Module 04',
                'issue' => 'Workshop cards are pointer-only',
                'where' => 'Workshop selection cards are non-focusable generic elements with click handlers; keyboard users cannot reach or activate them.',
                'why_it_matters' => 'Users who navigate by keyboard or assistive technology cannot complete a core task without a pointer device.',
                'source' => 'WCAG 2.1.1 Keyboard',
                'remediation' => 'Use real form controls or a fully keyboard-operable custom control with visible focus and activation support.',
                'verification' => 'Tab through the workshop selection and confirm the cards are not reachable or actionable without a mouse or touch pointer.',
                'grading_nuance' => 'Do not create a second keyboard failure elsewhere in the experience.',
            ],
            [
                'number' => 7,
                'stage' => 'Choose a Workshop',
                'module' => 'Module 04',
                'issue' => 'Important details appear only on hover',
                'where' => 'A workshop detail is revealed only on pointer hover; keyboard focus does not expose the same information.',
                'why_it_matters' => 'Some users cannot hover or may miss crucial prerequisite or accessibility information when making a workshop choice.',
                'source' => 'WCAG 2.1.1 Keyboard; hover/focus interaction guidance; visible and discoverable information',
                'remediation' => 'Present the key information in a way that is available without hover, such as persistent text or keyboard-reachable content outside the hover-only state.',
                'verification' => 'Test the workshop choice with keyboard focus and confirm the crucial information is available without a hover state.',
                'grading_nuance' => 'This should be a plausible UI pattern, not a cartoonishly broken tooltip or a second pointer-only control.',
            ],
            [
                'number' => 8,
                'stage' => 'Register',
                'module' => 'Module 05',
                'issue' => 'Email relies on placeholder text instead of a persistent visible label',
                'where' => 'Email Address includes a hidden label and only the placeholder “Email address *”.',
                'why_it_matters' => 'The field loses its purpose once the user begins typing, leaving no stable label for sighted and assistive technology users.',
                'source' => 'WCAG 3.3.2 Labels or Instructions; 1.3.1 Info and Relationships',
                'remediation' => 'Add and keep a visible label in place while keeping the placeholder as supplemental guidance only.',
                'verification' => 'Check the field before and after typing and confirm the field identity remains clear without relying on placeholder text.',
                'grading_nuance' => 'This is the deliberate missing-label issue. Do not add a second label elsewhere that eliminates the intended failure.',
            ],
            [
                'number' => 9,
                'stage' => 'Register',
                'module' => 'Module 05',
                'issue' => 'Phone format requirement is revealed only after failure',
                'where' => 'Phone Number shows a proper label but does not tell the user the accepted format until the user submits invalid data. The form accepts only (860) 555-1212.',
                'why_it_matters' => 'Users are asked to guess the required format and only learn it after making a mistake, creating unnecessary friction and confusion.',
                'source' => 'WCAG 3.3.2 Labels or Instructions; 3.3.3 Error Suggestion',
                'remediation' => 'Tell the user the expected format before or at the point of entry and use clear guidance that can be understood before submission fails.',
                'verification' => 'Attempt a valid phone format and an invalid variation, then confirm the requirement is communicated clearly at the correct moment.',
                'grading_nuance' => 'The correction suggestion is useful; the issue is the timing of the requirement, not the correction itself.',
            ],
            [
                'number' => 10,
                'stage' => 'Register',
                'module' => 'Module 05',
                'issue' => 'Dietary preference group lacks proper fieldset/legend structure',
                'where' => 'The dietary question is visually placed above radio buttons but is not grouped with a fieldset and legend or equivalent proper grouping mechanism.',
                'why_it_matters' => 'Assistive technology users lose the relationship between the question and the options, making the grouping less understandable and less robust.',
                'source' => 'WCAG 1.3.1 Info and Relationships; accessible form structure guidance',
                'remediation' => 'Use a fieldset and legend or another programmatically appropriate grouping structure for the question and its choices.',
                'verification' => 'Inspect the radio group with accessibility tooling and confirm the question/choice relationship is clear and programmatically associated.',
                'grading_nuance' => 'This is the one intentionally ungrouped choice set. Other radio groups should remain correctly structured.',
            ],
            [
                'number' => 11,
                'stage' => 'Register',
                'module' => 'Module 05',
                'issue' => 'Major/Program error relies mainly on red highlighting',
                'where' => 'When the field is blank, the field gets a red border and the summary says only “Please check the highlighted fields.”',
                'why_it_matters' => 'The user cannot tell which field is wrong or what information is missing, so the error is vague and not properly identified.',
                'source' => 'WCAG 3.3.1 Error Identification',
                'remediation' => 'Associate the error with the specific field and state exactly what is missing or incorrect, not just that something is highlighted.',
                'verification' => 'Leave the field blank and confirm the user can identify the missing information and the affected field without guessing.',
                'grading_nuance' => 'This is not a generic issue with all form errors; it is the specific empty-field summary pattern.',
            ],
            [
                'number' => 12,
                'stage' => 'Register',
                'module' => 'Module 05',
                'issue' => 'Validation clears valid workshop work',
                'where' => 'Any Stage 3 validation error preserves the current form values but clears the previously selected workshop from Stage 2.',
                'why_it_matters' => 'The interface discards state that was already valid and forces the user to rework a previous step without a clear recovery path.',
                'source' => 'WCAG 3.3.3 Error Suggestion; prevention and recovery guidance',
                'remediation' => 'Keep valid work intact and restore the selected workshop while clearly guiding the user back to the needed form correction.',
                'verification' => 'Trigger a Stage 3 error after selecting a workshop and confirm the workshop disappears unexpectedly even though the form data is otherwise retained.',
                'grading_nuance' => 'Do not clear the whole registration; the user should discover the lost workshop later, not immediately return to Stage 2.',
            ],
            [
                'number' => 13,
                'stage' => 'Review and Submit',
                'module' => 'Module 05',
                'issue' => 'Workshop omitted from review',
                'where' => 'The review screen lists personal data but omits the selected workshop even though it is essential to the registration.',
                'why_it_matters' => 'Users cannot verify the key choice that determines the event experience before finalizing the submission.',
                'source' => 'WCAG 3.3.4 Error Prevention (Legal, Financial, Data); review and recovery',
                'remediation' => 'Show the selected workshop on the review screen and provide an opportunity to confirm or update it before completion.',
                'verification' => 'Reach the review screen and confirm the chosen workshop is absent from the summary, making it impossible to verify before submission.',
                'grading_nuance' => 'The workshop is consequential; omission affects the ability to review before a final action.',
            ],
            [
                'number' => 14,
                'stage' => 'Review and Submit',
                'module' => 'Module 05',
                'issue' => 'Final submission cannot easily be corrected afterward',
                'where' => 'After complete registration, the success screen lists submitted information and offers only a return-to-challenge or reset path; there is no edit, undo, or return-to-registration action.',
                'why_it_matters' => 'The experience represents a consequential action with no reasonable post-submit correction route, which can create uncertainty and reduce user agency.',
                'source' => 'Error prevention and user recovery practices; review and confirmation best practices',
                'remediation' => 'Offer a clear correction or edit path before confirmation or provide a visible post-submit recovery option that can be used to fix an issue.',
                'verification' => 'Submit the form and confirm there is no practical route to correct the registration after completion beyond leaving the experience or resetting it.',
                'grading_nuance' => 'The point is not to invent a destructive edit flow; it is to show that the interface leaves the user with no meaningful recovery once committed.',
            ],
        ],
        'non_failures' => [
            [
                'title' => 'Visible and responsive event layout',
                'why' => 'The general registration experience is designed to be understandable and usable in normal pointer-based navigation, and the event information is presented clearly.',
            ],
            [
                'title' => 'Ordinary body text and native controls',
                'why' => 'Most controls, labels, and information outside the planned issues are implemented in a normal, reasonable way so students can distinguish genuine accessibility failures from design preferences.',
            ],
            [
                'title' => 'Reset and navigation controls',
                'why' => 'The Reset Experience and Return to Challenge controls are implemented accessibly and are not part of the intentionally broken behaviors.',
            ],
        ],
    ],
];
