<?php

return [
    'categories' => [
        [
            'title' => 'Foundations',
            'entries' => [
                [
                    'slug' => 'accessibility',
                    'title' => 'Accessibility',
                    'summary' => 'A quality standard for digital experiences: people with disabilities should be able to perceive, understand, navigate, and complete tasks with comparable independence.',
                    'in_this_course' => [
                        ['label' => 'Used in Module 01 - Accessible According to Whom?', 'route' => 'modules.show', 'params' => ['module' => 1]],
                        ['label' => 'Session 01 - Is This Accessible?', 'route' => 'modules.session', 'params' => ['module' => 1, 'session' => 1]],
                        ['label' => 'Challenge 01 brief', 'route' => 'modules.challenge', 'params' => ['module' => 1]],
                        ['label' => 'Design Futures 2026 Registration experience', 'route' => 'experiences.campus-event-registration'],
                    ],
                    'overview' => 'Accessibility is the practice of designing and evaluating digital experiences so disabled people can use them effectively in real contexts, not just pass a checklist.',
                    'why_it_matters' => 'If accessibility is treated as a vague opinion, teams ship barriers and cannot defend quality claims. Shared definitions help teams make accountable decisions.',
                    'what_to_look_for' => [
                        'Can people complete the primary task with a keyboard only?',
                        'Is critical information still clear at 200% zoom and in high-contrast conditions?',
                        'Are labels, instructions, and error messages explicit and persistent?',
                        'Do findings cite a source of authority, not only intuition or AI output?',
                    ],
                    'standards_guidance' => [
                        'WCAG gives technical conformance criteria that can support evidence.',
                        'Institutional and legal requirements determine accountability context.',
                        'No single source answers every accessibility question; triangulate evidence.',
                    ],
                    'resource_refs' => [
                        ['module' => 1, 'collection' => 'Start Here'],
                        ['module' => 1, 'collection' => 'Standards Lens'],
                        ['module' => 1, 'collection' => 'Legal Lens'],
                        ['module' => 1, 'collection' => 'Institutional Lens'],
                    ],
                    'related_entries' => ['wcag', 'pour', 'law-policy'],
                ],
                [
                    'slug' => 'disability-inclusive-design',
                    'title' => 'Disability & Inclusive Design',
                    'summary' => 'Designing with disability perspectives from the start improves outcomes for many users, not only edge cases.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['accessibility', 'cognitive-accessibility'],
                ],
                [
                    'slug' => 'wcag',
                    'title' => 'WCAG',
                    'summary' => 'The Web Content Accessibility Guidelines provide testable success criteria used internationally to evaluate conformance.',
                    'in_this_course' => [
                        ['label' => 'Used in Module 01 - Accessible According to Whom?', 'route' => 'modules.show', 'params' => ['module' => 1]],
                        ['label' => 'Session 02 - Build the Definition', 'route' => 'modules.session', 'params' => ['module' => 1, 'session' => 2]],
                        ['label' => 'Challenge 01 brief', 'route' => 'modules.challenge', 'params' => ['module' => 1]],
                    ],
                    'overview' => 'WCAG is a technical standard that helps teams evaluate whether web content meets accessibility requirements at Levels A, AA, and AAA.',
                    'why_it_matters' => 'WCAG gives consistent language for testing and remediation. It strengthens claims with criteria instead of preference-based debate.',
                    'what_to_look_for' => [
                        'Which success criterion is relevant to the issue you found?',
                        'What conformance level (A, AA, AAA) applies?',
                        'Can you connect your finding to the Understanding page or technique guidance?',
                        'What does the criterion cover, and what does it not prove?',
                    ],
                    'standards_guidance' => [
                        'Use WCAG 2.2 as the normative technical standard reference.',
                        'Use Understanding and Quick Reference to interpret and apply criteria.',
                        'Conformance evidence should include observed behavior and criterion mapping.',
                    ],
                    'resource_refs' => [
                        ['module' => 1, 'collection' => 'Start Here'],
                        ['module' => 1, 'collection' => 'Standards Lens'],
                    ],
                    'related_entries' => ['pour', 'testing-tools', 'accessibility'],
                ],
                [
                    'slug' => 'pour',
                    'title' => 'POUR',
                    'summary' => 'POUR (Perceivable, Operable, Understandable, Robust) is a practical map for organizing accessibility investigations.',
                    'in_this_course' => [
                        ['label' => 'Used in Module 01 - Accessible According to Whom?', 'route' => 'modules.show', 'params' => ['module' => 1]],
                        ['label' => 'Session 02 - Learn the Map', 'route' => 'modules.session', 'params' => ['module' => 1, 'session' => 2]],
                    ],
                    'overview' => 'POUR is the organizational structure behind WCAG. It helps you locate where an issue belongs before selecting specific criteria.',
                    'why_it_matters' => 'Without a clear map, teams miss issue classes and over-focus on what automated tools happen to detect.',
                    'what_to_look_for' => [
                        'Perceivable: Is important content presented in ways users can perceive?',
                        'Operable: Can users navigate and operate controls with available input methods?',
                        'Understandable: Are instructions, behavior, and errors predictable and clear?',
                        'Robust: Is content structured for compatibility across assistive technologies?',
                    ],
                    'standards_guidance' => [
                        'POUR principles are conceptual groupings, not pass/fail checks on their own.',
                        'Evidence is established at success-criterion level, then interpreted in context.',
                    ],
                    'resource_refs' => [
                        ['module' => 1, 'resource_label' => 'POUR Principles'],
                        ['module' => 1, 'collection' => 'Start Here'],
                        ['module' => 1, 'collection' => 'Standards Lens'],
                    ],
                    'related_entries' => ['wcag', 'accessibility'],
                ],
                [
                    'slug' => 'law-policy',
                    'title' => 'Law & Policy',
                    'summary' => 'Legal and institutional requirements define accountability, obligations, and risk for accessibility decisions.',
                    'in_this_course' => [
                        ['label' => 'Used in Module 01 - Accessible According to Whom?', 'route' => 'modules.show', 'params' => ['module' => 1]],
                        ['label' => 'Session 02 - Investigate Your Lens', 'route' => 'modules.session', 'params' => ['module' => 1, 'session' => 2]],
                        ['label' => 'Challenge 01 brief', 'route' => 'modules.challenge', 'params' => ['module' => 1]],
                    ],
                    'overview' => 'Accessibility work operates within distinct but related legal and institutional frameworks. Section 504 applies to federally funded programs and activities, ADA Title II applies to state and local public entities, and Section 508 governs federal-agency ICT. UConn policy then operationalizes requirements within its own context.',
                    'why_it_matters' => 'Design choices are not only usability decisions; they also sit within higher education equity, procurement, and accountability obligations. These frameworks overlap, but they are not interchangeable.',
                    'what_to_look_for' => [
                        'Section 504: What nondiscrimination obligations apply to federally funded educational programs and activities?',
                        'ADA Title II: What obligations apply to a public university as a state and local government entity?',
                        'Section 508: What does it require for federal-agency ICT, and how is that different from UConn\'s context?',
                        'UConn policy: What institutional requirements or procedures do students and teams need to understand in practice?',
                        'What can legal and policy sources establish, and what still requires testing and evaluation?',
                    ],
                    'standards_guidance' => [
                        'Section 504 is relevant to colleges and universities that receive federal financial assistance.',
                        'ADA Title II applies to public universities and now includes specific web and mobile accessibility requirements under the DOJ rule.',
                        'Section 508 directly covers federal-agency ICT, not all non-federal institutions.',
                        'UConn policy and procedures operationalize multiple frameworks and should be read in context, not collapsed into a generic "accessibility law" label.',
                    ],
                    'resource_refs' => [
                        ['module' => 1, 'collection' => 'Legal Lens'],
                        ['module' => 1, 'collection' => 'Institutional Lens'],
                    ],
                    'related_entries' => ['accessibility', 'wcag'],
                ],
            ],
        ],
        [
            'title' => 'Content & Perception',
            'entries' => [
                [
                    'slug' => 'color-contrast',
                    'title' => 'Color & Contrast',
                    'summary' => 'How color choices and contrast ratios affect readability and information access.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['typography-reflow', 'accessibility-audits'],
                ],
                [
                    'slug' => 'typography-reflow',
                    'title' => 'Typography & Reflow',
                    'summary' => 'Readable type, spacing, and responsive reflow are critical to sustained comprehension.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['color-contrast'],
                ],
                [
                    'slug' => 'alternative-text',
                    'title' => 'Alternative Text',
                    'summary' => 'Writing text alternatives that communicate the purpose and meaning of non-text content.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['screen-readers', 'semantic-html'],
                ],
                [
                    'slug' => 'audio-video-captions',
                    'title' => 'Audio, Video & Captions',
                    'summary' => 'Making time-based media understandable and navigable through captions, transcripts, and structure.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['cognitive-accessibility'],
                ],
            ],
        ],
        [
            'title' => 'Interaction',
            'entries' => [
                [
                    'slug' => 'keyboard',
                    'title' => 'Keyboard',
                    'summary' => 'Ensuring all core functionality works without a mouse.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['focus', 'forms-errors'],
                ],
                [
                    'slug' => 'focus',
                    'title' => 'Focus',
                    'summary' => 'Visible, predictable focus behavior supports navigation confidence and task completion.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['keyboard', 'forms-errors'],
                ],
                [
                    'slug' => 'forms-errors',
                    'title' => 'Forms & Errors',
                    'summary' => 'Labels, instructions, and error handling determine whether forms are actually usable.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['keyboard', 'focus'],
                ],
                [
                    'slug' => 'touch-mobile',
                    'title' => 'Touch & Mobile',
                    'summary' => 'Mobile interaction patterns must remain perceivable and operable across device contexts.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['motion-timing'],
                ],
            ],
        ],
        [
            'title' => 'Structure & Assistive Technology',
            'entries' => [
                [
                    'slug' => 'semantic-html',
                    'title' => 'Semantic HTML',
                    'summary' => 'Document structure and native semantics are foundational for robust accessibility.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['screen-readers', 'aria'],
                ],
                [
                    'slug' => 'screen-readers',
                    'title' => 'Screen Readers',
                    'summary' => 'How assistive technology users perceive structure, controls, announcements, and link purpose.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['semantic-html', 'alternative-text'],
                ],
                [
                    'slug' => 'aria',
                    'title' => 'ARIA',
                    'summary' => 'ARIA can improve custom UI semantics when native HTML cannot represent interaction patterns.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['semantic-html', 'screen-readers'],
                ],
            ],
        ],
        [
            'title' => 'Broader Practice',
            'entries' => [
                [
                    'slug' => 'uconn-accessibility-tools',
                    'title' => 'UConn Accessibility Tools',
                    'summary' => 'UConn\'s central guide to university-supported accessibility tools, assistive technologies, browser testing tools, coding guidance, and validators.',
                    'overview' => 'Use UConn\'s Accessibility Tools page as the institutional starting point. It is the clearest place to begin when the course needs to connect classroom testing to the university\'s supported tools, guidance, and institutional context.',
                    'why_it_matters' => 'This is the course\'s starting point for tools, assistive technologies, browser inspection, and guidance. It helps students understand the broader ecosystem without treating any one tool as a complete answer.',
                    'authoritative_resources' => [
                        ['source' => 'UConn', 'label' => 'UConn Accessibility Tools', 'href' => 'https://accessibility.its.uconn.edu/accessibility-tools/'],
                    ],
                    'related_entries' => ['toolkit', 'screen-readers', 'testing-workflow'],
                ],
                [
                    'slug' => 'nvda',
                    'title' => 'NVDA',
                    'summary' => 'Free, open-source screen reader for Windows. This course uses NVDA as the primary Windows screen-reader testing path.',
                    'overview' => 'NVDA is a free, widely used Windows screen reader. In this course it provides a practical route to testing headings, landmarks, links, forms, names, roles, states, and dynamic interface behavior.',
                    'why_it_matters' => 'Students can install and use NVDA on Windows without extra cost, which makes it a useful primary testing path for a class environment.',
                    'authoritative_resources' => [
                        ['source' => 'WebAIM', 'label' => 'WebAIM: Using NVDA to Evaluate Web Accessibility', 'href' => 'https://webaim.org/articles/nvda/'],
                        ['source' => 'NV Access', 'label' => 'NVDA', 'href' => 'https://www.nvaccess.org/'],
                    ],
                    'related_entries' => ['toolkit', 'screen-readers', 'testing-workflow'],
                ],
                [
                    'slug' => 'voiceover',
                    'title' => 'VoiceOver',
                    'summary' => 'Screen reader built into macOS and other Apple devices. Use it in Module 05 to test page structure, controls, and state announcements without relying on visual layout alone.',
                    'overview' => 'VoiceOver is the built-in macOS screen reader. It is one of the primary screen-reader paths used in this course because it is already available on common Apple hardware used in class and in many workflows.',
                    'why_it_matters' => 'Students can use it to evaluate headings, links, forms, landmarks, and state changes while working through the same page visually and with speech output.',
                    'authoritative_resources' => [
                        ['source' => 'WebAIM', 'label' => 'WebAIM: Using VoiceOver to Evaluate Web Accessibility', 'href' => 'https://webaim.org/articles/voiceover/'],
                        ['source' => 'Apple', 'label' => 'VoiceOver User Guide', 'href' => 'https://support.apple.com/guide/voiceover/'],
                    ],
                    'related_entries' => ['toolkit', 'screen-readers', 'testing-workflow'],
                ],
                [
                    'slug' => 'jaws',
                    'title' => 'JAWS',
                    'summary' => 'Commercial Windows screen reader. It is useful to know about, but it is not the required class path.',
                    'overview' => 'JAWS is a widely used Windows screen reader, but this course uses NVDA as the primary Windows testing path because it is free and accessible for class use.',
                    'why_it_matters' => 'Students should know JAWS exists in the broader ecosystem, but the teaching sequence is intentionally designed to stay practical and accessible for beginners.',
                    'authoritative_resources' => [
                        ['source' => 'UConn', 'label' => 'UConn Accessibility Tools', 'href' => 'https://accessibility.its.uconn.edu/accessibility-tools/'],
                        ['source' => 'Freedom Scientific', 'label' => 'JAWS', 'href' => 'https://www.freedomscientific.com/products/software/jaws/'],
                    ],
                    'related_entries' => ['toolkit', 'screen-readers'],
                ],
                [
                    'slug' => 'accessibility-bookmarklets',
                    'title' => 'Accessibility Bookmarklets',
                    'summary' => 'Browser bookmarklets that make hidden accessibility information visible, including headings, landmarks, labels, descriptions, and ARIA information.',
                    'overview' => 'Bookmarklets are a useful way to make hidden accessibility information visible without introducing a developer-only workflow. They are a great companion to a screen-reader check and a keyboard test.',
                    'why_it_matters' => 'These tools help make structure, semantics, and state visible, which is especially helpful when a UI looks fine but the underlying structure is weak.',
                    'authoritative_resources' => [
                        ['source' => 'Accessibility Bookmarklets', 'label' => 'Accessibility Bookmarklets', 'href' => 'https://accessibility-bookmarklets.org/'],
                    ],
                    'related_entries' => ['toolkit', 'testing-workflow', 'aria'],
                ],
                [
                    'slug' => 'toolkit',
                    'title' => 'Accessibility Toolkit',
                    'summary' => 'Practical tools and methods available throughout this course for testing, investigation, and evidence.',
                    'overview' => 'No single tool can prove whether an experience is accessible. Different tools provide different evidence. This toolkit collects tools you will use in this course, describes what each tool can show you, and clarifies what each tool cannot prove by itself.',
                    'why_it_matters' => 'A tool can provide evidence. A tool does not determine whether an experience is accessible. Using multiple tools and methods gives you stronger, more defensible conclusions.',
                    'sections' => [
                        [
                            'title' => 'UConn Accessibility Tools',
                            'description' => 'UConn\'s central guide to university-supported accessibility tools, assistive technologies, browser testing tools, coding guidance, and validators.',
                            'use_for' => [
                                'Finding the institutional starting point for supported tools and guidance',
                                'Locating assistive technologies and browser-based testing resources',
                                'Finding coding guidance and validator resources used by the university',
                            ],
                            'resources' => [
                                ['source' => 'UConn', 'label' => 'UConn Accessibility Tools', 'href' => 'https://accessibility.its.uconn.edu/accessibility-tools/'],
                            ],
                            'limitations' => 'The UConn page is a starting point for institutional guidance and tools. It is not itself a classroom audit or a determination that an experience is accessible.',
                        ],
                        [
                            'title' => 'NVDA',
                            'description' => 'Free, open-source screen reader for Windows. Use it in Module 05 to inspect headings, landmarks, links, controls, form labels, names, roles, states, and dynamic interface behavior.',
                            'use_for' => [
                                'Testing structure and hierarchy',
                                'Listening to names, roles, and states',
                                'Navigation without a mouse',
                                'Understanding how a form communicates its purpose and requirements',
                            ],
                            'resources' => [
                                ['source' => 'WebAIM', 'label' => 'WebAIM: Using NVDA to Evaluate Web Accessibility', 'href' => 'https://webaim.org/articles/nvda/'],
                                ['source' => 'NV Access', 'label' => 'NVDA', 'href' => 'https://www.nvaccess.org/'],
                            ],
                            'limitations' => 'A screen-reader result is evidence from a test, not proof that an interface is accessible or inaccessible. Practice is required to become comfortable with the tool.',
                        ],
                        [
                            'title' => 'VoiceOver',
                            'description' => 'Screen reader built into macOS and other Apple platforms. Use it in Module 05 to navigate page structure, controls, forms, images, and interface state without relying on the visual presentation.',
                            'use_for' => [
                                'Testing page structure and content flow',
                                'Understanding form labels, names, and state announcements',
                                'Checking whether interface changes are communicated',
                                'Navigating without visual inspection alone',
                            ],
                            'resources' => [
                                ['source' => 'WebAIM', 'label' => 'WebAIM: Using VoiceOver to Evaluate Web Accessibility', 'href' => 'https://webaim.org/articles/voiceover/'],
                                ['source' => 'Apple', 'label' => 'VoiceOver User Guide', 'href' => 'https://support.apple.com/guide/voiceover/'],
                            ],
                            'limitations' => 'A single VoiceOver pass is not the same as expert screen-reader usage. The goal is to understand the semantics and announcements that are exposed to users.',
                        ],
                        [
                            'title' => 'JAWS',
                            'description' => 'Commercial Windows screen reader widely used by people who are blind or have low vision.',
                            'use_for' => [
                                'Understanding the broader screen-reader ecosystem',
                                'Recognizing enterprise and professional testing contexts',
                                'Comparing institutional tool guidance against class practice',
                            ],
                            'resources' => [
                                ['source' => 'UConn', 'label' => 'UConn Accessibility Tools', 'href' => 'https://accessibility.its.uconn.edu/accessibility-tools/'],
                                ['source' => 'Freedom Scientific', 'label' => 'JAWS', 'href' => 'https://www.freedomscientific.com/products/software/jaws/'],
                            ],
                            'limitations' => 'JAWS is relevant as a technology reference, but this course uses NVDA as the primary Windows screen-reader path and does not require JAWS for assignments.',
                        ],
                        [
                            'title' => 'Accessibility Bookmarklets',
                            'description' => 'Browser bookmarklets that expose otherwise hidden accessibility information such as headings, landmarks, labels, descriptions, and ARIA information.',
                            'use_for' => [
                                'Making headings, landmarks, and controls visible on the page',
                                'Inspecting labels, image alternatives, and ARIA information',
                                'Comparing what is visible in the browser with what is exposed to assistive technology',
                            ],
                            'resources' => [
                                ['source' => 'Accessibility Bookmarklets', 'label' => 'Accessibility Bookmarklets', 'href' => 'https://accessibility-bookmarklets.org/'],
                            ],
                            'limitations' => 'Investigation aid, not a compliance result.',
                        ],
                        [
                            'title' => 'Browser Accessibility Tools',
                            'description' => 'Use the accessibility tools included in the browser you already have. The goal is to inspect what the browser exposes, not to learn every developer-tool interface.',
                            'use_for' => [
                                'Inspecting the accessibility tree',
                                'Reviewing names, roles, states, and relationships',
                                'Checking how the interface exposes semantics to assistive technologies',
                            ],
                            'resources' => [
                                ['source' => 'Chrome', 'label' => 'Chrome DevTools Accessibility Reference', 'href' => 'https://developer.chrome.com/docs/devtools/accessibility/reference/'],
                                ['source' => 'Firefox', 'label' => 'Firefox Accessibility Inspector', 'href' => 'https://firefox-source-docs.mozilla.org/devtools-user/accessibility_inspector/'],
                                ['source' => 'Microsoft Edge', 'label' => 'Microsoft Edge DevTools Accessibility', 'href' => 'https://learn.microsoft.com/microsoft-edge/devtools/accessibility/'],
                            ],
                            'limitations' => 'These tools reveal how the browser exposes semantics, but they do not tell you whether the task is usable for every person in context.',
                        ],
                        [
                            'title' => 'WAVE',
                            'description' => 'WebAIM WAVE browser extension and evaluation tool.',
                            'use_for' => [
                                'Identifying potential accessibility issues automatically',
                                'Visualizing page structure and heading hierarchy',
                                'Detecting missing alt text and form labels',
                                'Seeing at a glance how WAVE categorizes issues on a page',
                            ],
                            'how_to_access' => 'Use the online evaluation tool or install the browser extension for Chrome, Firefox, or Edge.',
                            'resources' => [
                                ['source' => 'WebAIM', 'label' => 'WAVE Web Accessibility Evaluation Tools', 'href' => 'https://wave.webaim.org/'],
                                ['source' => 'WebAIM', 'label' => 'WAVE Browser Extensions', 'href' => 'https://wave.webaim.org/extension/'],
                            ],
                            'limitations' => 'WAVE can identify many potential accessibility issues and expose page structure. Its output is not a determination that a page is accessible or inaccessible. WAVE cannot test keyboard interaction, zoom behavior, dynamic content, or real user experience.',
                        ],
                        [
                            'title' => 'Siteimprove',
                            'description' => 'University-supported web scanning and quality-assurance tool for accessibility, broken links, and content quality.',
                            'use_for' => [
                                'Scanning for accessibility issues and quality concerns across a site',
                                'Reviewing repeated patterns and larger site health issues',
                                'Supporting institutional monitoring and QA efforts',
                            ],
                            'how_to_access' => 'Access may require a university request or institutional configuration.',
                            'limitations' => 'Siteimprove is useful supporting evidence, but it does not replace direct testing or standards interpretation.',
                        ],
                        [
                            'title' => 'Accessibility Insights',
                            'description' => 'Microsoft accessibility checking and educational tool for evaluating common issues and understanding the context of findings.',
                            'use_for' => [
                                'Reviewing common automated checks',
                                'Supporting accessibility learning in a familiar tool environment',
                                'Cross-checking key issues with a second tool',
                            ],
                            'resources' => [
                                ['source' => 'Microsoft', 'label' => 'Accessibility Insights', 'href' => 'https://accessibilityinsights.io/'],
                            ],
                            'limitations' => 'It is not required for this course and should be used as supporting evidence, not as a substitute for direct testing.',
                        ],
                        [
                            'title' => 'axe',
                            'description' => 'Developer-oriented automated accessibility testing toolkit used in many engineering workflows.',
                            'use_for' => [
                                'Identifying common rule violations in code and browser tooling',
                                'Supporting engineering review and remediation',
                                'Cross-checking issues surfaced by other tools',
                            ],
                            'resources' => [
                                ['source' => 'Deque', 'label' => 'axe', 'href' => 'https://www.deque.com/axe/'],
                            ],
                            'limitations' => 'Automated tools can identify some accessibility problems. They cannot establish that an experience is accessible.',
                        ],
                        [
                            'title' => 'W3C HTML Validator',
                            'description' => 'HTML validator used to check whether markup is structurally valid.',
                            'use_for' => [
                                'Checking document validity and obvious markup problems',
                                'Validating HTML structure',
                                'Supporting a broader review of implementation quality',
                            ],
                            'resources' => [
                                ['source' => 'W3C', 'label' => 'W3C HTML Validator', 'href' => 'https://validator.w3.org/'],
                            ],
                            'limitations' => 'Valid HTML is not the same as accessible HTML. Validation helps, but it does not prove usability or full accessibility.',
                        ],
                        [
                            'title' => 'W3C CSS Validator',
                            'description' => 'CSS validator used to check syntax and quality of stylesheets.',
                            'use_for' => [
                                'Checking stylesheet validity',
                                'Checking for syntax problems and structural issues in CSS',
                                'Reviewing style-related problems attached to layout or contrast',
                            ],
                            'resources' => [
                                ['source' => 'W3C', 'label' => 'W3C CSS Validator', 'href' => 'https://jigsaw.w3.org/css-validator/'],
                            ],
                            'limitations' => 'CSS validity is useful but secondary. It does not establish that the visual or semantic experience is accessible.',
                        ],
                        [
                            'title' => 'ARIA Authoring Practices Guide',
                            'description' => 'W3C patterns, examples, and guidance for accessible widgets, names, landmarks, roles, states, and keyboard interaction.',
                            'use_for' => [
                                'Understanding how accessible widgets should behave',
                                'Checking names, roles, state changes, and keyboard interaction',
                                'Finding examples of accessible patterns to compare with a custom component',
                            ],
                            'resources' => [
                                ['source' => 'W3C WAI', 'label' => 'WAI-ARIA', 'href' => 'https://www.w3.org/WAI/standards-guidelines/aria/'],
                                ['source' => 'W3C WAI', 'label' => 'ARIA Authoring Practices Guide', 'href' => 'https://www.w3.org/WAI/ARIA/apg/'],
                            ],
                            'note' => 'Native HTML first. Add ARIA when the interface actually requires it. No ARIA is better than bad ARIA.',
                            'limitations' => 'ARIA is a support mechanism, not a substitute for semantic HTML or good design. It requires careful patterns and verification.',
                        ],
                    ],
                    'key_principle' => 'No single tool answers the question “Is this accessible?” Different tools reveal different parts of the interface.',
                    'testing_sequence' => [
                        'Understand the task. What is this interface trying to help a person do?',
                        'Test normal use. Can the task be completed without visual dependence on the design alone?',
                        'Test keyboard operation. Can the task still be completed without a mouse?',
                        'Check visual presentation and contrast. What is easy to read and distinguish?',
                        'Evaluate meaningful media. What information is carried by images, audio, or video?',
                        'Inspect semantic structure. What do headings, landmarks, labels, and naming reveal?',
                        'Test with a screen reader. What does the interface actually announce?',
                        'Trigger errors and state changes. What happens visually and programmatically?',
                        'Use automated tools as supporting evidence. What do they reveal and what do they miss?',
                        'Verify findings against authoritative guidance. What is the actual standard or principle behind the observation?',
                    ],
                    'related_entries' => ['uconn-accessibility-tools', 'nvda', 'voiceover', 'accessibility-bookmarklets', 'aria', 'wcag', 'screen-readers'],
                ],
                [
                    'slug' => 'testing-workflow',
                    'title' => 'Accessibility Testing Workflow',
                    'summary' => 'A durable workflow for investigating accessibility that synthesizes the course without turning testing into a checklist fetish.',
                    'overview' => 'This workflow helps students move from first impressions to evidence-based investigation. The point is not to memorize a sequence. The point is to know which kinds of evidence help answer which question about the interface.',
                    'why_it_matters' => 'Different tools reveal different parts of an interface. A single tool cannot answer the question “Is this accessible?” across all user needs and contexts.',
                    'testing_sequence' => [
                        'Understand the task.',
                        'Test normal use.',
                        'Test keyboard operation.',
                        'Check visual presentation and contrast.',
                        'Evaluate meaningful media.',
                        'Inspect semantic structure.',
                        'Test with a screen reader.',
                        'Trigger errors and state changes.',
                        'Use automated tools as supporting evidence.',
                        'Verify findings against authoritative guidance.',
                    ],
                    'related_entries' => ['uconn-accessibility-tools', 'toolkit', 'nvda', 'voiceover', 'accessibility-bookmarklets', 'aria'],
                ],
                [
                    'slug' => 'cognitive-accessibility',
                    'title' => 'Cognitive Accessibility',
                    'summary' => 'Reducing unnecessary cognitive load through language, structure, and interaction clarity.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['motion-timing'],
                ],
                [
                    'slug' => 'motion-timing',
                    'title' => 'Motion & Timing',
                    'summary' => 'Animation, timing limits, and interruption behavior can create barriers if not carefully designed.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['touch-mobile', 'cognitive-accessibility'],
                ],
                [
                    'slug' => 'ai-accessibility',
                    'title' => 'AI & Accessibility',
                    'summary' => 'AI can accelerate analysis and prototyping, but outputs must be verified with authoritative evidence.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['testing-tools', 'accessibility-audits'],
                ],
                [
                    'slug' => 'testing-tools',
                    'title' => 'Testing Tools',
                    'summary' => 'Automated and manual tools support investigation, but no single tool can prove full accessibility.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['toolkit', 'accessibility-audits', 'wcag'],
                ],
                [
                    'slug' => 'accessibility-audits',
                    'title' => 'Accessibility Audits',
                    'summary' => 'A structured evaluation process combining standards mapping, manual testing, and prioritization.',
                    'status_note' => 'Expanded guidance will be added when we reach this topic.',
                    'related_entries' => ['testing-tools', 'toolkit', 'accessibility'],
                ],
            ],
        ],
    ],
];
